import { useCallback, useEffect, useRef, useState } from "react";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";
import type { UIMessage } from "ai";
import { MoreVertical } from "lucide-react";
import { Conversation } from "@/components/ai-elements/conversation";
import { AssistantThinkingMessage, Message } from "@/components/ai-elements/message";
import { ChatInput, type ChatToolOption } from "@/components/chat/ChatInput";
import { ConversationContextMenu } from "@/components/chat/ConversationContextMenu";
import { SuggestedMessages } from "@/components/chat/SuggestedMessages";
import { DEFAULT_CHAT_MODEL_ID, getChatModelConfig, type ChatModelId } from "@/shared/chat-models";
import { useAppStore } from "@/lib/store";
import { isVizArtifactCandidate, normalizeVizToolName } from "@/lib/viz-helpers";
import { Button, Input } from "@/components/ui/primitives";
import type { ChatConversation } from "@/lib/types";
import type { ParsedDocument } from "@/lib/document-parser";
import type { PromptInputSubmitPayload } from "@/components/ai-elements/prompt-input";
import { buildChartSpecFromVizHint, isChartSpec } from "@/lib/viz-data-parser";
import type { ResumableChatJobPayload } from "@/shared/resumable-chat";

type Part = { type: string; [key: string]: unknown };
type PersistedMessage = {
  id: string;
  role: "user" | "assistant";
  parts: Part[];
  created_at: string;
};
type ToolsCatalogResponse = {
  items?: ChatToolOption[];
  tools?: ChatToolOption[];
  totalCount?: number;
  nextOffset?: number | null;
  hasMore?: boolean;
};
type ToolsCacheEntry = {
  items: ChatToolOption[];
  totalCount: number;
  nextOffset: number | null;
  hasMore: boolean;
};
type ModelUsageResponse = {
  banner: string | null;
  approaching: boolean;
  reached: boolean;
};
type CouncilScope = { kind: "postcode"; postcode: string } | { kind: "area"; area: string } | { kind: "national" };
const AUTO_CHAT_TITLE_DEFAULT_REGEX = /^(new chat(?:\s+\d+)?|untitled)$/i;
const UK_POSTCODE_REGEX = /\b([A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2})\b/i;
const OPTIMISTIC_CHAT_ID_PREFIX = "optimistic-chat-";
const NEW_CONVERSATION_DRAFT_KEY = "__new-conversation__";

async function safeJson<T>(response: Response): Promise<T | null> {
  const text = await response.text();
  if (!text) return null;
  try {
    return JSON.parse(text) as T;
  } catch {
    return null;
  }
}

function formatDocumentFailures(failures: Array<{ name: string; error: string }>): string {
  if (failures.length === 0) return "";
  const topFailures = failures.slice(0, 3).map((failure) => `${failure.name}: ${failure.error}`);
  const suffix = failures.length > 3 ? ` (+${failures.length - 3} more)` : "";
  return `Some documents could not be used: ${topFailures.join(" | ")}${suffix}`;
}

function isAutoGeneratedTitle(title?: string | null): boolean {
  if (!title) return true;
  return AUTO_CHAT_TITLE_DEFAULT_REGEX.test(title.trim());
}

function formatChatErrorMessage(message: string | undefined): string {
  if (!message) return "Something went wrong sending your message. Please try again.";
  try {
    const parsed = JSON.parse(message) as { code?: number; message?: string; metadata?: { error_type?: string } };
    if (parsed.code === 400 || parsed.metadata?.error_type === "invalid_request") {
      return "This model cannot handle that request. Try rephrasing or switching to a different model.";
    }
    if (typeof parsed.message === "string" && parsed.message.trim()) return parsed.message;
  } catch {
    // Not JSON; fall through to the original message.
  }
  return message;
}

function stableStringify(value: unknown): string {
  if (value == null) return "";
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

function hashString(input: string): string {
  let hash = 0;
  for (let index = 0; index < input.length; index += 1) {
    hash = (hash * 31 + input.charCodeAt(index)) | 0;
  }
  return Math.abs(hash).toString(36);
}

function isOptimisticConversationId(value: string | null | undefined): boolean {
  return typeof value === "string" && value.startsWith(OPTIMISTIC_CHAT_ID_PREFIX);
}

function hasRenderableAssistantPart(part: Part): boolean {
  if (part.type === "step-start") return false;
  if (part.type === "reasoning" || part.type === "tool-invocation" || part.type.startsWith("tool-")) return true;
  if (part.type !== "text") return false;
  const candidate = part as { text?: unknown; content?: unknown; value?: unknown };
  const value = candidate.text ?? candidate.content ?? candidate.value;
  return typeof value === "string" && value.trim().length > 0;
}

export function ChatView({
  conversation,
  conversationId,
  mcpToken,
  authToken,
  onEnsureConversation,
  onRenameConversation,
  onConversationMissing,
  onDeleteConversation,
  onToggleStarConversation,
  onShareConversation,
  onUnshareConversation,
}: {
  conversation: ChatConversation | null;
  conversationId: string | null;
  mcpToken: string | null;
  authToken: string | null;
  onEnsureConversation: () => Promise<string | null>;
  onRenameConversation: (id: string, title: string) => void;
  onConversationMissing: (id: string) => Promise<void> | void;
  onDeleteConversation: (id: string) => void;
  onToggleStarConversation: (id: string, starred: boolean) => void;
  onShareConversation: (conversation: ChatConversation) => void;
  onUnshareConversation: (conversation: ChatConversation) => void;
}) {
  const pushVizPayload = useAppStore((state) => state.pushVizPayload);
  const pinnedArtifacts = useAppStore((state) => state.pinnedArtifacts);
  const clearPinnedArtifacts = useAppStore((state) => state.clearPinnedArtifacts);
  const unpinArtifact = useAppStore((state) => state.unpinArtifact);
  const setConversations = useAppStore((state) => state.setConversations);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [conversationLoadError, setConversationLoadError] = useState<string | null>(null);
  const [editingTitle, setEditingTitle] = useState(false);
  const [draftTitle, setDraftTitle] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedModelId, setSelectedModelId] = useState<ChatModelId>(DEFAULT_CHAT_MODEL_ID);
  const selectedModel = getChatModelConfig(selectedModelId);
  const [toolsLoading, setToolsLoading] = useState(false);
  const [toolsLoadingMore, setToolsLoadingMore] = useState(false);
  const [toolsQuery, setToolsQuery] = useState<string | null>(null);
  const [tools, setTools] = useState<ChatToolOption[]>([]);
  const [toolsTotalCount, setToolsTotalCount] = useState(0);
  const [toolsNextOffset, setToolsNextOffset] = useState<number | null>(0);
  const [toolsHasMore, setToolsHasMore] = useState(false);
  const [selectedTools, setSelectedTools] = useState<ChatToolOption[]>([]);
  const [usageBanner, setUsageBanner] = useState<string | null>(null);
  const [councilModeEnabled, setCouncilModeEnabled] = useState(false);
  const [draftsByConversation, setDraftsByConversation] = useState<Record<string, string>>({});
  const [councilPending, setCouncilPending] = useState(false);
  const [pendingConversationId, setPendingConversationId] = useState<string | null>(null);
  const [preparingConversation, setPreparingConversation] = useState(false);
  const [resumablePending, setResumablePending] = useState(false);
  const toolsCacheRef = useRef<Map<string, ToolsCacheEntry>>(new Map());
  const titleMenuRef = useRef<HTMLDivElement | null>(null);
  const pushedArtifactKeysRef = useRef<Set<string>>(new Set());
  const artifactSignaturesRef = useRef<Map<string, string>>(new Map());
  const liveSessionConversationIdRef = useRef<string | null>(null);
  const onMissingRef = useRef(onConversationMissing);
  onMissingRef.current = onConversationMissing;

  const fetchToolsPage = useCallback(
    async ({
      query,
      offset,
      signal,
    }: {
      query: string;
      offset: number;
      signal: AbortSignal;
    }): Promise<ToolsCacheEntry> => {
      if (!authToken || !mcpToken) {
        throw new Error("Missing auth or MCP token.");
      }
      const response = await fetch("/api/chat/tools", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${authToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ mcpToken, query, offset, limit: 50 }),
        signal,
      });
      if (!response.ok) throw new Error(`Failed to load tools (${response.status})`);
      const payload = (await safeJson<ToolsCatalogResponse>(response)) ?? {};
      const items = payload.items ?? payload.tools ?? [];
      const totalCount = payload.totalCount ?? items.length;
      const nextOffset = payload.nextOffset ?? null;
      const hasMore = payload.hasMore ?? nextOffset !== null;
      return { items, totalCount, nextOffset, hasMore };
    },
    [authToken, mcpToken],
  );

  useEffect(() => {
    toolsCacheRef.current.clear();
    setTools([]);
    setToolsTotalCount(0);
    setToolsNextOffset(0);
    setToolsHasMore(false);
  }, [authToken, mcpToken]);

  useEffect(() => {
    if (!authToken || !mcpToken) {
      setTools([]);
      setToolsLoading(false);
      setToolsLoadingMore(false);
      setToolsHasMore(false);
      setToolsNextOffset(0);
      return;
    }
    if (toolsQuery === null) {
      setToolsLoading(false);
      setToolsLoadingMore(false);
      return;
    }
    const queryKey = toolsQuery.trim().toLowerCase();
    const cached = toolsCacheRef.current.get(queryKey);
    if (cached) {
      setTools(cached.items);
      setToolsTotalCount(cached.totalCount);
      setToolsNextOffset(cached.nextOffset);
      setToolsHasMore(cached.hasMore);
      setToolsLoading(false);
      return;
    }

    const abortController = new AbortController();
    const timeoutId = window.setTimeout(() => {
      void fetchToolsPage({
        query: queryKey,
        offset: 0,
        signal: abortController.signal,
      })
        .then((page) => {
          if (abortController.signal.aborted || !page) return;
          toolsCacheRef.current.set(queryKey, page);
          setTools(page.items);
          setToolsTotalCount(page.totalCount);
          setToolsNextOffset(page.nextOffset);
          setToolsHasMore(page.hasMore);
        })
        .catch(() => {
          if (abortController.signal.aborted) return;
          setTools([]);
          setToolsHasMore(false);
          setToolsNextOffset(null);
        })
        .finally(() => {
          if (!abortController.signal.aborted) setToolsLoading(false);
        });
    }, 160);

    setToolsLoading(true);
    setToolsLoadingMore(false);
    setTools([]);
    setToolsNextOffset(0);
    setToolsHasMore(false);
    setToolsTotalCount(0);
    return () => {
      window.clearTimeout(timeoutId);
      abortController.abort();
    };
  }, [authToken, mcpToken, fetchToolsPage, toolsQuery]);

  useEffect(() => {
    setSelectedTools((current) => current.filter((selected) => tools.some((tool) => tool.name === selected.name)));
  }, [tools]);

  useEffect(() => {
    setDraftTitle(conversation?.title ?? "");
    setEditingTitle(false);
    setMenuOpen(false);
  }, [conversation?.id, conversation?.title]);

  useEffect(() => {
    if (!menuOpen) return;

    function handleDocumentMouseDown(event: MouseEvent) {
      const target = event.target;
      if (!(target instanceof Node)) return;
      if (titleMenuRef.current?.contains(target)) return;
      setMenuOpen(false);
    }

    function handleEscape(event: KeyboardEvent) {
      if (event.key !== "Escape") return;
      setMenuOpen(false);
    }

    document.addEventListener("mousedown", handleDocumentMouseDown);
    document.addEventListener("keydown", handleEscape);
    return () => {
      document.removeEventListener("mousedown", handleDocumentMouseDown);
      document.removeEventListener("keydown", handleEscape);
    };
  }, [menuOpen]);

  const refreshUsageBanner = useCallback(async () => {
    if (!authToken) {
      setUsageBanner(null);
      return;
    }
    try {
      const response = await fetch(`/api/chat/usage?modelId=${encodeURIComponent(selectedModel.id)}`, {
        headers: { Authorization: `Bearer ${authToken}` },
      });
      if (!response.ok) return;
      const payload = await safeJson<ModelUsageResponse>(response);
      setUsageBanner(payload?.banner ?? null);
    } catch {
      // Optional banner only; ignore transient failures.
    }
  }, [authToken, selectedModel.id]);

  useEffect(() => {
    setSubmitError(null);
    void refreshUsageBanner();
  }, [refreshUsageBanner, selectedModelId]);

  useEffect(() => {
    if (!authToken) {
      setUsageBanner(null);
      return;
    }
    void refreshUsageBanner();
  }, [authToken, refreshUsageBanner]);

  const { messages, status, setMessages } = useChat({
    transport: new DefaultChatTransport({
      api: "/api/chat",
    }),
    onError: (error) => {
      setSubmitError(formatChatErrorMessage(error.message));
    },
  });

  useEffect(() => {
    const activeConversationId = conversationId ?? pendingConversationId;
    if (!activeConversationId) {
      liveSessionConversationIdRef.current = null;
      return;
    }
    // Keep the live-session lock while parent state transitions through optimistic IDs.
    if (isOptimisticConversationId(activeConversationId)) return;
    if (liveSessionConversationIdRef.current && liveSessionConversationIdRef.current !== activeConversationId) {
      liveSessionConversationIdRef.current = null;
    }
  }, [conversationId, pendingConversationId]);

  const loadConversationMessages = useCallback(
    async (targetConversationId: string) => {
      if (!authToken) return;
      const response = await fetch(`/api/conversations/${targetConversationId}`, {
        headers: { Authorization: `Bearer ${authToken}` },
      });
      if (!response.ok) return;
      const payload = (await safeJson<{ messages?: PersistedMessage[] }>(response)) ?? { messages: [] };
      const mapped: UIMessage[] = (payload.messages ?? []).map((message) => ({
        id: message.id,
        role: message.role === "assistant" ? "assistant" : "user",
        parts: (message.parts ?? []) as UIMessage["parts"],
      }));
      setMessages(mapped);
    },
    [authToken, setMessages],
  );

  function extractAreaCandidate(text: string): string | null {
    const compact = text.replace(/\s+/g, " ").trim();
    const patterns = [
      /\bconstituency\s+([a-z0-9][a-z0-9\s'&-]{2,60}?)(?:\b(?:for|on|about|regarding|with|where|which)\b|[,.!?;]|$)/i,
      /\b(?:in|for|around|near)\s+([a-z][a-z\s'&-]{2,50}?)(?:\b(?:for|on|about|regarding|with|where|which)\b|[,.!?;]|$)/i,
    ];
    for (const pattern of patterns) {
      const match = compact.match(pattern);
      const candidate = match?.[1]?.trim();
      if (!candidate) continue;
      if (["my area", "the area", "my constituency", "the constituency"].includes(candidate.toLowerCase())) continue;
      return candidate.replace(/[,.!?;]+$/, "");
    }
    return null;
  }

  function inferCouncilScopeDeterministic(text: string): CouncilScope {
    const postcodeMatch = text.match(UK_POSTCODE_REGEX);
    if (postcodeMatch?.[1]) {
      return { kind: "postcode", postcode: postcodeMatch[1].replace(/\s+/g, "").toUpperCase() };
    }
    const area = extractAreaCandidate(text);
    if (area) {
      return { kind: "area", area };
    }
    return { kind: "national" };
  }

  async function inferCouncilScopeFromText(text: string): Promise<CouncilScope> {
    const deterministic = inferCouncilScopeDeterministic(text);
    if (deterministic.kind === "postcode") return deterministic;
    if (!authToken) return deterministic;
    try {
      const response = await fetch("/api/council/infer-scope", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${authToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text,
          modelId: selectedModelId,
        }),
      });
      if (!response.ok) return deterministic;
      const payload = await safeJson<{ scope?: CouncilScope }>(response);
      if (!payload?.scope || typeof payload.scope.kind !== "string") return deterministic;
      if (payload.scope.kind === "postcode" && typeof payload.scope.postcode === "string") return payload.scope;
      if (payload.scope.kind === "area" && typeof payload.scope.area === "string") return payload.scope;
      if (payload.scope.kind === "national") return payload.scope;
      return deterministic;
    } catch {
      return deterministic;
    }
  }

  function extractLatestCouncilIdFromMessages(inputMessages: UIMessage[]): string | null {
    const latestAssistant = [...inputMessages].reverse().find((message) => message.role === "assistant" && Array.isArray(message.parts));
    if (!latestAssistant || !Array.isArray(latestAssistant.parts)) return null;
    for (const part of latestAssistant.parts as Part[]) {
      if (!part.type?.startsWith("tool-") || !("output" in part)) continue;
      if (part.type.replace("tool-", "") !== "council_deliberation") continue;
      const output = part.output;
      if (!output || typeof output !== "object") continue;
      const id = (output as { councilId?: unknown }).councilId;
      if (typeof id === "string" && id.trim()) return id;
    }
    return null;
  }

  async function submitPrompt(payload: PromptInputSubmitPayload): Promise<boolean> {
    const text = payload.text;
    const needsConversationCreation = !conversationId;
    if (needsConversationCreation) {
      setPreparingConversation(true);
    }
    setSubmitError(null);
    if (!authToken) {
      setSubmitError("You need to sign in before sending a message.");
      return false;
    }
    if (!mcpToken) {
      setSubmitError("Your access token is still being prepared. Please try again in a few seconds.");
      return false;
    }
    const ensuredConversationId = conversationId ?? (await onEnsureConversation());
    if (!ensuredConversationId) {
      setPreparingConversation(false);
      setSubmitError("Could not create a conversation. Please try again.");
      return false;
    }
    setPreparingConversation(false);
    setPendingConversationId(ensuredConversationId);
    liveSessionConversationIdRef.current = ensuredConversationId;
    const shouldRefreshAutoTitle = messages.length === 0 && isAutoGeneratedTitle(conversation?.title);
    if (payload.mode === "council") {
      const optimisticMessageId = `optimistic-council-${crypto.randomUUID()}`;
      setMessages((current) => [
        ...current,
        {
          id: optimisticMessageId,
          role: "user",
          parts: [{ type: "text", text }],
        } as UIMessage,
      ]);
      setCouncilPending(true);
      const latestCouncilId = extractLatestCouncilIdFromMessages(messages as UIMessage[]);
      if (latestCouncilId) {
        void (async () => {
          try {
            const followupResponse = await fetch("/api/council/followup", {
              method: "POST",
              headers: {
                Authorization: `Bearer ${authToken}`,
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                councilId: latestCouncilId,
                followUp: text,
                modelId: selectedModelId,
                mcpToken,
              }),
            });
            if (!followupResponse.ok) {
              const errorPayload = await safeJson<{ error?: string }>(followupResponse);
              setSubmitError(errorPayload?.error ?? `Failed to update council (${followupResponse.status})`);
              setMessages((current) => current.filter((message) => message.id !== optimisticMessageId));
              setCouncilPending(false);
              return;
            }
            await loadConversationMessages(ensuredConversationId);
            setCouncilPending(false);
            window.setTimeout(() => {
              void refreshUsageBanner();
            }, 1200);
          } catch (error) {
            setSubmitError(error instanceof Error ? error.message : "Failed to update council.");
            setMessages((current) => current.filter((message) => message.id !== optimisticMessageId));
            setCouncilPending(false);
          }
        })();
        return true;
      }

      void (async () => {
        try {
          const scope = await inferCouncilScopeFromText(text);
          const createResponse = await fetch("/api/council", {
            method: "POST",
            headers: {
              Authorization: `Bearer ${authToken}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              conversationId: ensuredConversationId,
              issue: text,
              scope,
              modelId: selectedModelId,
              mcpToken,
            }),
          });
          if (!createResponse.ok) {
            const errorPayload = await safeJson<{ error?: string }>(createResponse);
            setSubmitError(errorPayload?.error ?? `Failed to create council (${createResponse.status})`);
            setMessages((current) => current.filter((message) => message.id !== optimisticMessageId));
            setCouncilPending(false);
            return;
          }
          await loadConversationMessages(ensuredConversationId);
          setCouncilPending(false);
          window.setTimeout(() => {
            void refreshUsageBanner();
          }, 1200);
        } catch (error) {
          setSubmitError(error instanceof Error ? error.message : "Failed to create council.");
          setMessages((current) => current.filter((message) => message.id !== optimisticMessageId));
          setCouncilPending(false);
        }
      })();
      return true;
    }

    const toolPrefix =
      selectedTools.length > 0
        ? `Use these tools when relevant: ${selectedTools.map((tool) => `/${tool.name}`).join(" ")}\n\n`
        : "";
    let parsedDocuments: ParsedDocument[] = [];
    if (payload.documents.length > 0) {
      const { parseDocuments } = await import("@/lib/document-parser");
      const parsedResult = await parseDocuments(payload.documents);
      parsedDocuments = parsedResult.documents;
      if (parsedResult.failures.length > 0) {
        setSubmitError(formatDocumentFailures(parsedResult.failures));
      }
      if (parsedDocuments.length === 0) {
        if (parsedResult.failures.length === 0) {
          setSubmitError("No readable text could be extracted from the selected documents.");
        }
        return false;
      }
    }

    const submittedText = `${toolPrefix}${text}`;
    const optimisticMessageId = `optimistic-user-${crypto.randomUUID()}`;
    const optimisticMessages = [
      ...messages,
      {
        id: optimisticMessageId,
        role: "user",
        parts: [{ type: "text", text: submittedText }],
      } as UIMessage,
    ];
    setMessages(optimisticMessages);
    setResumablePending(true);
    void (async () => {
      let finalStatus: ResumableChatJobPayload["status"] | null = null;
      let finalError: string | null = null;
      try {
        const createResponse = await fetch("/api/chat/jobs", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${authToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            conversationId: ensuredConversationId,
            mcpToken,
            modelId: selectedModel.id,
            documents: parsedDocuments,
            artifactContext: pinnedArtifacts.map((artifact) => ({
              id: artifact.id,
              conversationId: artifact.conversationId,
              messageId: artifact.messageId,
              toolName: artifact.toolName,
              title: artifact.title,
              data: artifact.data,
              chartSpec: artifact.chartSpec,
            })),
            messages: optimisticMessages.map((message) => ({ role: message.role, parts: message.parts })),
            idempotencyKey: crypto.randomUUID(),
          }),
        });
        const createPayload = await safeJson<{ job?: ResumableChatJobPayload; error?: string }>(createResponse);
        if (!createResponse.ok || !createPayload?.job) {
          throw new Error(createPayload?.error ?? `Failed to start resumable chat (${createResponse.status})`);
        }
        let job = createPayload.job;
        const streamingAssistantMessageId = `streaming-assistant-${job.id}`;
        let guard = 0;
        while (job.status === "in_progress" && guard < 32) {
          guard += 1;
          const continueResponse = await fetch(`/api/chat/jobs/${job.id}/continue`, {
            method: "POST",
            headers: {
              Authorization: `Bearer ${authToken}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              mcpToken,
              idempotencyKey: `${job.id}-${guard}-${Date.now()}`,
            }),
          });
          const continuePayload = await safeJson<{ job?: ResumableChatJobPayload; error?: string }>(continueResponse);
          if (!continueResponse.ok || !continuePayload?.job) {
            throw new Error(continuePayload?.error ?? `Failed to continue chat (${continueResponse.status})`);
          }
          job = continuePayload.job;
          if (Array.isArray(job.assistantParts) && job.assistantParts.length > 0) {
            setMessages([
              ...optimisticMessages,
              {
                id: streamingAssistantMessageId,
                role: "assistant",
                parts: job.assistantParts as UIMessage["parts"],
              } as UIMessage,
            ]);
          }
        }
        finalStatus = job.status;
        if (Array.isArray(job.assistantParts) && job.assistantParts.length > 0) {
          setMessages([
            ...optimisticMessages,
            {
              id: streamingAssistantMessageId,
              role: "assistant",
              parts: job.assistantParts as UIMessage["parts"],
            } as UIMessage,
          ]);
        }
        if (job.status === "failed") {
          finalError = job.lastError ?? "The assistant couldn't finish that response. Please try again.";
        }
      } catch (error) {
        finalStatus = "failed";
        finalError = error instanceof Error ? error.message : "Failed to send your message.";
      } finally {
        await loadConversationMessages(ensuredConversationId);
        if (finalStatus === "failed" && finalError) setSubmitError(finalError);
        if (finalStatus === "completed") clearPinnedArtifacts();
        setResumablePending(false);
        setSelectedTools([]);
        window.setTimeout(() => {
          void refreshUsageBanner();
        }, 1200);
      }
    })();
    if (shouldRefreshAutoTitle && authToken) {
      void (async () => {
        for (let attempt = 0; attempt < 4; attempt += 1) {
          await new Promise((resolve) => window.setTimeout(resolve, 900 * (attempt + 1)));
          const response = await fetch(`/api/conversations/${ensuredConversationId}`, {
            headers: { Authorization: `Bearer ${authToken}` },
          });
          if (!response.ok) continue;
          const payload = await safeJson<{ conversation?: ChatConversation }>(response);
          const serverConversation = payload?.conversation;
          if (!serverConversation || isAutoGeneratedTitle(serverConversation.title)) continue;
          const currentConversations = useAppStore.getState().conversations;
          const nextConversations = currentConversations.map((item) =>
            item.id === ensuredConversationId ? { ...item, title: serverConversation.title, updated_at: serverConversation.updated_at } : item,
          );
          nextConversations.sort((a, b) => {
            if (a.starred !== b.starred) return a.starred ? -1 : 1;
            return new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime();
          });
          setConversations(nextConversations);
          break;
        }
      })();
    }
    return true;
  }

  function toggleToolSelection(tool: ChatToolOption) {
    setSelectedTools((current) => {
      const exists = current.some((selected) => selected.name === tool.name);
      if (exists) return current.filter((selected) => selected.name !== tool.name);
      return [...current, tool];
    });
  }

  function handleToolsQueryChange(query: string | null) {
    setToolsQuery(query);
  }

  function handleLoadMoreTools() {
    if (!authToken || !mcpToken) return;
    if (toolsQuery === null) return;
    if (!toolsHasMore || toolsLoadingMore || toolsNextOffset == null) return;
    const abortController = new AbortController();
    setToolsLoadingMore(true);
    const queryKey = toolsQuery.trim().toLowerCase();
    void fetchToolsPage({
      query: queryKey,
      offset: toolsNextOffset,
      signal: abortController.signal,
    })
      .then((page) => {
        if (abortController.signal.aborted || !page) return;
        setTools((prev) => {
          const map = new Map(prev.map((tool) => [tool.name, tool] as const));
          page.items.forEach((tool) => map.set(tool.name, tool));
          const merged = [...map.values()];
          toolsCacheRef.current.set(queryKey, {
            items: merged,
            totalCount: page.totalCount,
            nextOffset: page.nextOffset,
            hasMore: page.hasMore,
          });
          return merged;
        });
        setToolsTotalCount(page.totalCount);
        setToolsNextOffset(page.nextOffset);
        setToolsHasMore(page.hasMore);
      })
      .catch(() => {
        // Non-blocking incremental load.
      })
      .finally(() => {
        setToolsLoadingMore(false);
      });
  }

  useEffect(() => {
    if (conversationId && pendingConversationId === conversationId) {
      setPendingConversationId(null);
    }
  }, [conversationId, pendingConversationId]);

  useEffect(() => {
    if (!conversationId) return;
    setPreparingConversation(false);
  }, [conversationId]);

  useEffect(() => {
    pushedArtifactKeysRef.current.clear();
    artifactSignaturesRef.current.clear();
    setConversationLoadError(null);
    const activeConversationId = conversationId ?? pendingConversationId;
    if (!authToken) {
      setMessages([]);
      return;
    }
    if (!activeConversationId) {
      setPendingConversationId(null);
      setMessages([]);
      return;
    }
    if (!conversationId && pendingConversationId) {
      // Keep optimistic/prefetched messages while parent conversation state catches up.
      return;
    }
    if (!conversationId) {
      setMessages([]);
      return;
    }
    const requestedConversationId = activeConversationId;
    if (isOptimisticConversationId(requestedConversationId)) {
      return;
    }
    if (liveSessionConversationIdRef.current === requestedConversationId) {
      return;
    }
    const abortController = new AbortController();
    fetch(`/api/conversations/${requestedConversationId}`, { headers: { Authorization: `Bearer ${authToken}` }, signal: abortController.signal })
      .then(async (response) => {
        if (response.status === 404) {
          await onMissingRef.current(requestedConversationId);
          return null;
        }
        if (!response.ok) throw new Error(`Failed to load conversation (${response.status})`);
        return (await safeJson<{ messages?: PersistedMessage[] }>(response)) ?? { messages: [] };
      })
      .then((payload) => {
        if (abortController.signal.aborted || !payload) return;
        const mapped: UIMessage[] = (payload.messages ?? []).map((message) => ({
          id: message.id,
          role: message.role === "assistant" ? "assistant" : "user",
          parts: (message.parts ?? []) as UIMessage["parts"],
        }));
        setMessages(mapped);
      })
      .catch((error) => {
        if (abortController.signal.aborted || error instanceof DOMException) return;
        setConversationLoadError("Couldn't load this conversation. Try again or start a new chat.");
        setMessages([]);
      });
    return () => {
      abortController.abort();
    };
  }, [authToken, conversationId, pendingConversationId, setMessages]);

  useEffect(() => {
    for (const message of messages) {
      if (message.role !== "assistant" || !Array.isArray(message.parts)) continue;

      (message.parts as Part[]).forEach((part, index) => {
        let toolName: string | undefined;
        let toolCallId: string | undefined;
        let output: unknown;

        if (part.type === "tool-invocation") {
          const inv = (part as { toolInvocation?: { toolName: string; toolCallId: string; state: string; result?: unknown } }).toolInvocation;
          if (!inv || inv.state !== "result" || inv.result == null) return;
          toolName = inv.toolName;
          toolCallId = inv.toolCallId;
          output = inv.result;
        } else if (part.type.startsWith("tool-")) {
          if (part.state !== "output-available" || !("output" in part) || part.output == null) return;
          toolName = part.type.replace("tool-", "");
          toolCallId = typeof part.toolCallId === "string" ? part.toolCallId : undefined;
          output = part.output;
        } else {
          return;
        }

        if (!toolName || !isVizArtifactCandidate(toolName, output)) return;
        const normalizedToolName = normalizeVizToolName(toolName);
        const chartSpec =
          normalizedToolName === "create_chart" && isChartSpec(output)
            ? output
            : buildChartSpecFromVizHint(output);
        const fallbackId = `sig-${hashString(`${normalizedToolName}:${stableStringify(output).slice(0, 1200)}`)}`;
        const id = toolCallId ?? fallbackId;
        const artifactKey = `${message.id}:${normalizedToolName}:${id}`;
        const signature = `${stableStringify(output).slice(0, 12000)}|${stableStringify(chartSpec).slice(0, 12000)}`;
        if (pushedArtifactKeysRef.current.has(artifactKey) && artifactSignaturesRef.current.get(artifactKey) === signature) return;
        pushedArtifactKeysRef.current.add(artifactKey);
        artifactSignaturesRef.current.set(artifactKey, signature);
        pushVizPayload({
          id: artifactKey,
          toolName: normalizedToolName,
          data: output,
          title: `Chart: ${normalizedToolName}`,
          chartSpec: chartSpec ?? undefined,
          conversationId: conversationId ?? undefined,
          messageId: message.id,
        });
      });
    }
  }, [conversationId, messages, pushVizPayload]);

  function submitTitleRename() {
    if (!conversation) return;
    const trimmed = draftTitle.trim();
    if (!trimmed || trimmed === conversation.title.trim()) {
      setEditingTitle(false);
      setDraftTitle(conversation.title);
      return;
    }
    onRenameConversation(conversation.id, trimmed);
    setEditingTitle(false);
  }

  const titleInputWidthCh = Math.min(48, Math.max(12, draftTitle.trim().length + 2));
  const composerDraftKey = conversationId ?? NEW_CONVERSATION_DRAFT_KEY;
  const composerDraft = draftsByConversation[composerDraftKey] ?? "";

  const handleComposerDraftChange = useCallback(
    (nextDraft: string) => {
      setDraftsByConversation((current) => {
        const existing = current[composerDraftKey] ?? "";
        if (nextDraft === existing) return current;
        if (!nextDraft) {
          if (!(composerDraftKey in current)) return current;
          const { [composerDraftKey]: _removed, ...rest } = current;
          return rest;
        }
        return { ...current, [composerDraftKey]: nextDraft };
      });
    },
    [composerDraftKey],
  );

  let lastUserMessageIndex = -1;
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    if (messages[index]?.role === "user") {
      lastUserMessageIndex = index;
      break;
    }
  }
  const lastAssistantMessage = [...messages.slice(lastUserMessageIndex + 1)].reverse().find((message) => message.role === "assistant");
  const hasAssistantContent =
    Array.isArray(lastAssistantMessage?.parts) && (lastAssistantMessage.parts as Part[]).some(hasRenderableAssistantPart);
  const showThinkingIndicator = (status === "submitted" || status === "streaming" || resumablePending) && !hasAssistantContent;
  const showCouncilThinkingIndicator = councilPending && (status !== "submitted" && status !== "streaming");
  const showPreConversationLoading = preparingConversation && messages.length === 0;

  return (
    <section className="flex h-full flex-col">
      <div className="sticky top-0 z-20 bg-(--color-background)/95 px-12 py-3 backdrop-blur-sm md:px-5">
        <div className="w-full">
          <div className="flex items-center justify-start gap-2 text-left">
            {editingTitle && conversation ? (
              <form
                className="shrink-0"
                onSubmit={(event) => {
                  event.preventDefault();
                  submitTitleRename();
                }}
              >
                <Input
                  value={draftTitle}
                  className="h-8 text-sm"
                  style={{ width: `${titleInputWidthCh}ch` }}
                  onChange={(event) => setDraftTitle(event.target.value)}
                  onBlur={submitTitleRename}
                  onKeyDown={(event) => {
                    if (event.key === "Escape") {
                      event.preventDefault();
                      setEditingTitle(false);
                      setDraftTitle(conversation.title);
                    }
                  }}
                  autoFocus
                />
              </form>
            ) : (
              <button
                type="button"
                className="max-w-[70vw] truncate text-center text-sm font-medium hover:opacity-80 md:max-w-[560px] md:text-left"
                onClick={() => {
                  if (!conversation) return;
                  setDraftTitle(conversation.title);
                  setEditingTitle(true);
                }}
                disabled={!conversation}
                aria-label={conversation ? "Rename conversation" : "Conversation title"}
              >
                {conversation?.title ?? "New conversation"}
              </button>
            )}
            <div className="relative" ref={titleMenuRef}>
              <Button
                type="button"
                variant="ghost"
                className="h-7 w-7 p-0"
                aria-label={conversation ? `Open actions for ${conversation.title}` : "Conversation actions"}
                onClick={() => setMenuOpen((current) => !current)}
                disabled={!conversation}
              >
                <MoreVertical className="h-4 w-4" />
              </Button>
              {menuOpen && conversation ? (
                <ConversationContextMenu
                  conversation={conversation}
                  className="absolute right-0 top-9 z-50 min-w-40 rounded-md border border-(--color-border) bg-(--color-background) p-1 text-left shadow-xl"
                  onRename={() => {
                    setDraftTitle(conversation.title);
                    setEditingTitle(true);
                    setMenuOpen(false);
                  }}
                  onToggleStar={() => {
                    onToggleStarConversation(conversation.id, !conversation.starred);
                    setMenuOpen(false);
                  }}
                  onShare={() => {
                    onShareConversation(conversation);
                    setMenuOpen(false);
                  }}
                  onUnshare={() => {
                    onUnshareConversation(conversation);
                    setMenuOpen(false);
                  }}
                  onDelete={() => {
                    onDeleteConversation(conversation.id);
                    setMenuOpen(false);
                  }}
                />
              ) : null}
            </div>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto px-6 py-6 md:px-12">
        <div className="mx-auto w-full md:max-w-[clamp(0px,calc(100vw-600px),860px)]">
          {messages.length === 0 && !showPreConversationLoading ? (
            <div className="mx-auto max-w-2xl space-y-4 pt-[20vh]">
              <h2 className="font-display text-2xl">Ask a UK question</h2>
              <p className="text-sm text-(--color-muted-foreground)">
                Answers are grounded in live UK data tools and rendered with maps, dashboards, and synthetic personas.
              </p>
              {conversationLoadError ? <p role="alert" className="text-sm text-(--color-muted-foreground)">{conversationLoadError}</p> : null}
              <SuggestedMessages
                councilModeEnabled={councilModeEnabled}
                onPick={({ text, mode }) => void submitPrompt({ text, documents: [], mode })}
                onSwitchToCouncilMode={() => setCouncilModeEnabled(true)}
              />
            </div>
          ) : (
            <Conversation>
              {messages.map((message) => (
                <Message key={message.id} message={message} />
              ))}
              {showPreConversationLoading ? <AssistantThinkingMessage /> : null}
              {showThinkingIndicator ? <AssistantThinkingMessage /> : null}
              {showCouncilThinkingIndicator ? <AssistantThinkingMessage /> : null}
            </Conversation>
          )}
        </div>
      </div>

      <div className="sticky bottom-0 bg-(--color-background) px-6 py-3 md:px-12">
        <div className="mx-auto w-full md:max-w-[clamp(0px,calc(100vw-600px),860px)]">
          {usageBanner ? (
            <p className="mb-2 rounded-md border border-[color-mix(in_oklch,var(--color-warning)_35%,transparent)] bg-[color-mix(in_oklch,var(--color-warning)_10%,transparent)] px-2 py-1.5 text-xs text-(--color-warning-foreground)">
              {usageBanner}
            </p>
          ) : null}
          {submitError ? (
            <p role="alert" className="mb-2 text-xs text-(--color-muted-foreground)">
              {submitError}
            </p>
          ) : null}
          <ChatInput
            value={composerDraft}
            onValueChange={handleComposerDraftChange}
            onSubmit={(payload) => void submitPrompt(payload)}
            onCouncilModeChange={setCouncilModeEnabled}
            councilModeEnabled={councilModeEnabled}
            isStreaming={status === "streaming" || status === "submitted" || councilPending || preparingConversation || resumablePending}
            modelId={selectedModelId}
            onModelChange={setSelectedModelId}
            tools={tools}
            toolsLoading={toolsLoading}
            toolsHasMore={toolsHasMore}
            toolsLoadingMore={toolsLoadingMore}
            selectedTools={selectedTools}
            onToggleToolSelection={toggleToolSelection}
            onToolsQueryChange={handleToolsQueryChange}
            onLoadMoreTools={handleLoadMoreTools}
            pinnedArtifacts={pinnedArtifacts}
            onRemovePinnedArtifact={unpinArtifact}
          />
          {councilModeEnabled ? (
            <p className="mt-2 text-xs text-(--color-muted-foreground)">
              Council mode is on. Include a postcode or constituency name for a local MP+councillors council; otherwise a national MPs council is created.
            </p>
          ) : null}
        </div>
      </div>
    </section>
  );
}
