import { useCallback, useEffect, useRef, useState } from "react";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";
import type { UIMessage } from "ai";
import { Conversation } from "@/components/ai-elements/conversation";
import { AssistantThinkingMessage, Message } from "@/components/ai-elements/message";
import { ChatInput, type ChatToolOption } from "@/components/chat/ChatInput";
import { SuggestedMessages } from "@/components/chat/SuggestedMessages";
import { DEFAULT_CHAT_MODEL_ID, getChatModelConfig, type ChatModelId } from "@/shared/chat-models";
import { useAppStore } from "@/lib/store";
import { isChartArtifactCandidate, normalizeVizToolName } from "@/lib/viz-registry";
import { Input } from "@/components/ui/primitives";
import type { ChatConversation } from "@/lib/types";
import { parseDocuments, type ParsedDocument } from "@/lib/document-parser";
import type { PromptInputSubmitPayload } from "@/components/ai-elements/prompt-input";
import { buildChartSpecFromVizHint, isChartSpec } from "@/lib/viz-data-parser";

type Part = { type: string; [key: string]: unknown };
type PersistedMessage = {
  id: string;
  role: "user" | "assistant";
  parts: Part[];
  created_at: string;
};
type ToolsCatalogResponse = {
  items?: ChatToolOption[];
  tools?: ChatToolOption[];
  totalCount?: number;
  nextOffset?: number | null;
  hasMore?: boolean;
};
type ToolsCacheEntry = {
  items: ChatToolOption[];
  totalCount: number;
  nextOffset: number | null;
  hasMore: boolean;
};
type ModelUsageResponse = {
  banner: string | null;
  approaching: boolean;
  reached: boolean;
};

const AUTO_CHAT_TITLE_DEFAULT_REGEX = /^(new chat(?:\s+\d+)?|untitled)$/i;

async function safeJson<T>(response: Response): Promise<T | null> {
  const text = await response.text();
  if (!text) return null;
  try {
    return JSON.parse(text) as T;
  } catch {
    return null;
  }
}

function formatDocumentFailures(failures: Array<{ name: string; error: string }>): string {
  if (failures.length === 0) return "";
  const topFailures = failures.slice(0, 3).map((failure) => `${failure.name}: ${failure.error}`);
  const suffix = failures.length > 3 ? ` (+${failures.length - 3} more)` : "";
  return `Some documents could not be used: ${topFailures.join(" | ")}${suffix}`;
}

function isAutoGeneratedTitle(title?: string | null): boolean {
  if (!title) return true;
  return AUTO_CHAT_TITLE_DEFAULT_REGEX.test(title.trim());
}

function formatChatErrorMessage(message: string | undefined): string {
  if (!message) return "Request failed. Please try again.";
  try {
    const parsed = JSON.parse(message) as { code?: number; message?: string; metadata?: { error_type?: string } };
    if (parsed.code === 400 || parsed.metadata?.error_type === "invalid_request") {
      return "The selected model rejected this request format. Please retry or switch model.";
    }
    if (typeof parsed.message === "string" && parsed.message.trim()) return parsed.message;
  } catch {
    // Not JSON; fall through to the original message.
  }
  return message;
}

function stableStringify(value: unknown): string {
  if (value == null) return "";
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

function hashString(input: string): string {
  let hash = 0;
  for (let index = 0; index < input.length; index += 1) {
    hash = (hash * 31 + input.charCodeAt(index)) | 0;
  }
  return Math.abs(hash).toString(36);
}

export function ChatView({
  conversation,
  conversationId,
  mcpToken,
  authToken,
  onEnsureConversation,
  onRenameConversation,
  onConversationMissing,
}: {
  conversation: ChatConversation | null;
  conversationId: string | null;
  mcpToken: string | null;
  authToken: string | null;
  onEnsureConversation: () => Promise<string | null>;
  onRenameConversation: (id: string, title: string) => void;
  onConversationMissing: (id: string) => Promise<void> | void;
}) {
  const pushVizPayload = useAppStore((state) => state.pushVizPayload);
  const clearVizPayloads = useAppStore((state) => state.clearVizPayloads);
  const setConversations = useAppStore((state) => state.setConversations);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [editingTitle, setEditingTitle] = useState(false);
  const [draftTitle, setDraftTitle] = useState("");
  const [selectedModelId, setSelectedModelId] = useState<ChatModelId>(DEFAULT_CHAT_MODEL_ID);
  const selectedModel = getChatModelConfig(selectedModelId);
  const [toolsLoading, setToolsLoading] = useState(false);
  const [toolsLoadingMore, setToolsLoadingMore] = useState(false);
  const [toolsQuery, setToolsQuery] = useState<string | null>(null);
  const [tools, setTools] = useState<ChatToolOption[]>([]);
  const [toolsTotalCount, setToolsTotalCount] = useState(0);
  const [toolsNextOffset, setToolsNextOffset] = useState<number | null>(0);
  const [toolsHasMore, setToolsHasMore] = useState(false);
  const [selectedTools, setSelectedTools] = useState<ChatToolOption[]>([]);
  const [usageBanner, setUsageBanner] = useState<string | null>(null);
  const toolsCacheRef = useRef<Map<string, ToolsCacheEntry>>(new Map());
  const pushedArtifactKeysRef = useRef<Set<string>>(new Set());
  const artifactSignaturesRef = useRef<Map<string, string>>(new Map());
  const onMissingRef = useRef(onConversationMissing);
  onMissingRef.current = onConversationMissing;

  const fetchToolsPage = useCallback(
    async ({
      query,
      offset,
      signal,
    }: {
      query: string;
      offset: number;
      signal: AbortSignal;
    }): Promise<ToolsCacheEntry> => {
      if (!authToken || !mcpToken) {
        throw new Error("Missing auth or MCP token.");
      }
      const response = await fetch("/api/chat/tools", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${authToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ mcpToken, query, offset, limit: 50 }),
        signal,
      });
      if (!response.ok) throw new Error(`Failed to load tools (${response.status})`);
      const payload = (await safeJson<ToolsCatalogResponse>(response)) ?? {};
      const items = payload.items ?? payload.tools ?? [];
      const totalCount = payload.totalCount ?? items.length;
      const nextOffset = payload.nextOffset ?? null;
      const hasMore = payload.hasMore ?? nextOffset !== null;
      return { items, totalCount, nextOffset, hasMore };
    },
    [authToken, mcpToken],
  );

  useEffect(() => {
    toolsCacheRef.current.clear();
    setTools([]);
    setToolsTotalCount(0);
    setToolsNextOffset(0);
    setToolsHasMore(false);
  }, [authToken, mcpToken]);

  useEffect(() => {
    if (!authToken || !mcpToken) {
      setTools([]);
      setToolsLoading(false);
      setToolsLoadingMore(false);
      setToolsHasMore(false);
      setToolsNextOffset(0);
      return;
    }
    if (toolsQuery === null) {
      setToolsLoading(false);
      setToolsLoadingMore(false);
      return;
    }
    const queryKey = toolsQuery.trim().toLowerCase();
    const cached = toolsCacheRef.current.get(queryKey);
    if (cached) {
      setTools(cached.items);
      setToolsTotalCount(cached.totalCount);
      setToolsNextOffset(cached.nextOffset);
      setToolsHasMore(cached.hasMore);
      setToolsLoading(false);
      return;
    }

    const abortController = new AbortController();
    const timeoutId = window.setTimeout(() => {
      void fetchToolsPage({
        query: queryKey,
        offset: 0,
        signal: abortController.signal,
      })
        .then((page) => {
          if (abortController.signal.aborted || !page) return;
          toolsCacheRef.current.set(queryKey, page);
          setTools(page.items);
          setToolsTotalCount(page.totalCount);
          setToolsNextOffset(page.nextOffset);
          setToolsHasMore(page.hasMore);
        })
        .catch(() => {
          if (abortController.signal.aborted) return;
          setTools([]);
          setToolsHasMore(false);
          setToolsNextOffset(null);
        })
        .finally(() => {
          if (!abortController.signal.aborted) setToolsLoading(false);
        });
    }, 160);

    setToolsLoading(true);
    setToolsLoadingMore(false);
    setTools([]);
    setToolsNextOffset(0);
    setToolsHasMore(false);
    setToolsTotalCount(0);
    return () => {
      window.clearTimeout(timeoutId);
      abortController.abort();
    };
  }, [authToken, mcpToken, fetchToolsPage, toolsQuery]);

  useEffect(() => {
    setSelectedTools((current) => current.filter((selected) => tools.some((tool) => tool.name === selected.name)));
  }, [tools]);

  useEffect(() => {
    setDraftTitle(conversation?.title ?? "");
    setEditingTitle(false);
  }, [conversation?.id, conversation?.title]);

  useEffect(() => {
    setSubmitError(null);
    void refreshUsageBanner();
  }, [selectedModelId]);

  useEffect(() => {
    if (!authToken) {
      setUsageBanner(null);
      return;
    }
    void refreshUsageBanner();
  }, [authToken]);

  const { messages, sendMessage, status, setMessages } = useChat({
    transport: new DefaultChatTransport({
      api: "/api/chat",
    }),
    onError: (error) => {
      setSubmitError(formatChatErrorMessage(error.message));
    },
  });

  async function submitPrompt(payload: PromptInputSubmitPayload) {
    const text = payload.text;
    setSubmitError(null);
    if (!authToken) {
      setSubmitError("You need to sign in before sending a message.");
      return;
    }
    if (!mcpToken) {
      setSubmitError("Your access token is still being prepared. Please try again in a few seconds.");
      return;
    }
    const ensuredConversationId = conversationId ?? (await onEnsureConversation());
    if (!ensuredConversationId) {
      setSubmitError("Could not create a conversation. Please try again.");
      return;
    }
    const shouldRefreshAutoTitle = messages.length === 0 && isAutoGeneratedTitle(conversation?.title);
    const toolPrefix =
      selectedTools.length > 0
        ? `Use these tools when relevant: ${selectedTools.map((tool) => `/${tool.name}`).join(" ")}\n\n`
        : "";
    let parsedDocuments: ParsedDocument[] = [];
    if (payload.documents.length > 0) {
      const parsedResult = await parseDocuments(payload.documents);
      parsedDocuments = parsedResult.documents;
      if (parsedResult.failures.length > 0) {
        setSubmitError(formatDocumentFailures(parsedResult.failures));
      }
      if (parsedDocuments.length === 0) {
        if (parsedResult.failures.length === 0) {
          setSubmitError("No readable text could be extracted from the selected documents.");
        }
        return;
      }
    }

    sendMessage(
      { text: `${toolPrefix}${text}` },
      {
        headers: authToken ? { Authorization: `Bearer ${authToken}` } : undefined,
        body: { conversationId: ensuredConversationId, mcpToken, modelId: selectedModel.id, documents: parsedDocuments },
      },
    );
    if (shouldRefreshAutoTitle && authToken) {
      void (async () => {
        for (let attempt = 0; attempt < 4; attempt += 1) {
          await new Promise((resolve) => window.setTimeout(resolve, 900 * (attempt + 1)));
          const response = await fetch(`/api/conversations/${ensuredConversationId}`, {
            headers: { Authorization: `Bearer ${authToken}` },
          });
          if (!response.ok) continue;
          const payload = await safeJson<{ conversation?: ChatConversation }>(response);
          const serverConversation = payload?.conversation;
          if (!serverConversation || isAutoGeneratedTitle(serverConversation.title)) continue;
          const currentConversations = useAppStore.getState().conversations;
          const nextConversations = currentConversations.map((item) =>
            item.id === ensuredConversationId ? { ...item, title: serverConversation.title, updated_at: serverConversation.updated_at } : item,
          );
          nextConversations.sort((a, b) => {
            if (a.starred !== b.starred) return a.starred ? -1 : 1;
            return new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime();
          });
          setConversations(nextConversations);
          break;
        }
      })();
    }
    setSelectedTools([]);
    window.setTimeout(() => {
      void refreshUsageBanner();
    }, 1200);
  }

  function toggleToolSelection(tool: ChatToolOption) {
    setSelectedTools((current) => {
      const exists = current.some((selected) => selected.name === tool.name);
      if (exists) return current.filter((selected) => selected.name !== tool.name);
      return [...current, tool];
    });
  }

  function handleToolsQueryChange(query: string | null) {
    setToolsQuery(query);
  }

  function handleLoadMoreTools() {
    if (!authToken || !mcpToken) return;
    if (toolsQuery === null) return;
    if (!toolsHasMore || toolsLoadingMore || toolsNextOffset == null) return;
    const abortController = new AbortController();
    setToolsLoadingMore(true);
    const queryKey = toolsQuery.trim().toLowerCase();
    void fetchToolsPage({
      query: queryKey,
      offset: toolsNextOffset,
      signal: abortController.signal,
    })
      .then((page) => {
        if (abortController.signal.aborted || !page) return;
        setTools((prev) => {
          const map = new Map(prev.map((tool) => [tool.name, tool] as const));
          page.items.forEach((tool) => map.set(tool.name, tool));
          const merged = [...map.values()];
          toolsCacheRef.current.set(queryKey, {
            items: merged,
            totalCount: page.totalCount,
            nextOffset: page.nextOffset,
            hasMore: page.hasMore,
          });
          return merged;
        });
        setToolsTotalCount(page.totalCount);
        setToolsNextOffset(page.nextOffset);
        setToolsHasMore(page.hasMore);
      })
      .catch(() => {
        // Non-blocking incremental load.
      })
      .finally(() => {
        setToolsLoadingMore(false);
      });
  }

  async function refreshUsageBanner() {
    if (!authToken) {
      setUsageBanner(null);
      return;
    }
    try {
      const response = await fetch(`/api/chat/usage?modelId=${encodeURIComponent(selectedModel.id)}`, {
        headers: { Authorization: `Bearer ${authToken}` },
      });
      if (!response.ok) return;
      const payload = await safeJson<ModelUsageResponse>(response);
      setUsageBanner(payload?.banner ?? null);
    } catch {
      // Optional banner only; ignore transient failures.
    }
  }

  useEffect(() => {
    pushedArtifactKeysRef.current.clear();
    artifactSignaturesRef.current.clear();
    clearVizPayloads();
    if (!conversationId || !authToken) {
      setMessages([]);
      return;
    }
    const requestedConversationId = conversationId;
    const abortController = new AbortController();
    fetch(`/api/conversations/${requestedConversationId}`, {
      headers: { Authorization: `Bearer ${authToken}` },
      signal: abortController.signal,
    })
      .then(async (response) => {
        if (response.status === 404) {
          await onMissingRef.current(requestedConversationId);
          return null;
        }
        if (!response.ok) throw new Error(`Failed to load conversation (${response.status})`);
        return (await safeJson<{ messages?: PersistedMessage[] }>(response)) ?? { messages: [] };
      })
      .then((payload) => {
        if (abortController.signal.aborted || !payload) return;
        const mapped: UIMessage[] = (payload.messages ?? []).map((message) => ({
          id: message.id,
          role: message.role === "assistant" ? "assistant" : "user",
          parts: (message.parts ?? []) as UIMessage["parts"],
        }));
        setMessages(mapped);
      })
      .catch((error) => {
        if (abortController.signal.aborted || error instanceof DOMException) return;
        setMessages([]);
      });
    return () => {
      abortController.abort();
    };
  }, [authToken, clearVizPayloads, conversationId, setMessages]);

  useEffect(() => {
    for (const message of messages) {
      if (message.role !== "assistant" || !Array.isArray(message.parts)) continue;

      (message.parts as Part[]).forEach((part, index) => {
        let toolName: string | undefined;
        let toolCallId: string | undefined;
        let output: unknown;

        if (part.type === "tool-invocation") {
          const inv = (part as { toolInvocation?: { toolName: string; toolCallId: string; state: string; result?: unknown } }).toolInvocation;
          if (!inv || inv.state !== "result" || inv.result == null) return;
          toolName = inv.toolName;
          toolCallId = inv.toolCallId;
          output = inv.result;
        } else if (part.type.startsWith("tool-")) {
          if (part.state !== "output-available" || !("output" in part) || part.output == null) return;
          toolName = part.type.replace("tool-", "");
          toolCallId = typeof part.toolCallId === "string" ? part.toolCallId : undefined;
          output = part.output;
        } else {
          return;
        }

        if (!toolName || !isChartArtifactCandidate(toolName, output)) return;
        const normalizedToolName = normalizeVizToolName(toolName);
        const chartSpec =
          normalizedToolName === "create_chart" && isChartSpec(output)
            ? output
            : buildChartSpecFromVizHint(output);
        const fallbackId = `sig-${hashString(`${normalizedToolName}:${stableStringify(output).slice(0, 1200)}`)}`;
        const id = toolCallId ?? fallbackId;
        const artifactKey = `${message.id}:${normalizedToolName}:${id}`;
        const signature = `${stableStringify(output).slice(0, 12000)}|${stableStringify(chartSpec).slice(0, 12000)}`;
        if (pushedArtifactKeysRef.current.has(artifactKey) && artifactSignaturesRef.current.get(artifactKey) === signature) return;
        pushedArtifactKeysRef.current.add(artifactKey);
        artifactSignaturesRef.current.set(artifactKey, signature);
        pushVizPayload({
          id: artifactKey,
          toolName: normalizedToolName,
          data: output,
          title: `Chart: ${normalizedToolName}`,
          chartSpec: chartSpec ?? undefined,
        });
      });
    }
  }, [messages, pushVizPayload]);

  function submitTitleRename() {
    if (!conversation) return;
    const trimmed = draftTitle.trim();
    if (!trimmed || trimmed === conversation.title.trim()) {
      setEditingTitle(false);
      setDraftTitle(conversation.title);
      return;
    }
    onRenameConversation(conversation.id, trimmed);
    setEditingTitle(false);
  }

  const lastMessage = messages.at(-1);
  const hasAssistantContent =
    lastMessage?.role === "assistant" &&
    Array.isArray(lastMessage.parts) &&
    lastMessage.parts.some((part) => {
      if (part.type === "text") return typeof part.text === "string" && part.text.trim().length > 0;
      if (part.type === "reasoning") return true;
      if (part.type.startsWith("tool-")) return true;
      return false;
    });
  const showThinkingIndicator = (status === "submitted" || status === "streaming") && !hasAssistantContent;

  return (
    <section className="flex h-full flex-col">
      <div className="sticky top-0 z-20 bg-(--color-background)/95 px-12 py-3 backdrop-blur-sm md:px-12">
        <div className="mx-auto w-full md:max-w-[clamp(0px,calc(100vw-600px),860px)]">
          <div className="flex items-center justify-center gap-3 text-center md:justify-start md:text-left">
            {editingTitle && conversation ? (
              <form
                className="min-w-0 flex-1"
                onSubmit={(event) => {
                  event.preventDefault();
                  submitTitleRename();
                }}
              >
                <Input
                  value={draftTitle}
                  className="h-8 text-sm"
                  onChange={(event) => setDraftTitle(event.target.value)}
                  onBlur={submitTitleRename}
                  onKeyDown={(event) => {
                    if (event.key === "Escape") {
                      event.preventDefault();
                      setEditingTitle(false);
                      setDraftTitle(conversation.title);
                    }
                  }}
                  autoFocus
                />
              </form>
            ) : (
              <button
                type="button"
                className="min-w-0 truncate text-center text-sm font-medium hover:opacity-80 md:text-left"
                onClick={() => {
                  if (!conversation) return;
                  setDraftTitle(conversation.title);
                  setEditingTitle(true);
                }}
                disabled={!conversation}
                aria-label={conversation ? "Rename conversation" : "Conversation title"}
              >
                {conversation?.title ?? "New conversation"}
              </button>
            )}
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto px-6 py-6 md:px-12">
        <div className="mx-auto w-full md:max-w-[clamp(0px,calc(100vw-600px),860px)]">
          {messages.length === 0 ? (
            <div className="mx-auto max-w-2xl space-y-4 pt-[20vh]">
              <h2 className="font-display text-2xl">Ask a UK question</h2>
              <p className="text-sm text-(--color-muted-foreground)">
                Answers are grounded in live UK data tools and rendered with maps, dashboards, and synthetic personas.
              </p>
              <SuggestedMessages onPick={(text) => void submitPrompt({ text, documents: [] })} />
            </div>
          ) : (
            <Conversation>
              {messages.map((message) => (
                <Message key={message.id} message={message} />
              ))}
              {showThinkingIndicator ? <AssistantThinkingMessage /> : null}
            </Conversation>
          )}
        </div>
      </div>

      <div className="sticky bottom-0 bg-(--color-background) px-6 py-3 md:px-12">
        <div className="mx-auto w-full md:max-w-[clamp(0px,calc(100vw-600px),860px)]">
          {usageBanner ? (
            <p className="mb-2 rounded-md border border-amber-500/35 bg-amber-500/10 px-2 py-1.5 text-xs text-amber-200">{usageBanner}</p>
          ) : null}
          {submitError ? <p className="mb-2 text-xs text-(--color-muted-foreground)">{submitError}</p> : null}
          <ChatInput
            onSubmit={(payload) => void submitPrompt(payload)}
            isStreaming={status === "streaming" || status === "submitted"}
            modelId={selectedModelId}
            onModelChange={setSelectedModelId}
            tools={tools}
            toolsLoading={toolsLoading}
            toolsHasMore={toolsHasMore}
            toolsLoadingMore={toolsLoadingMore}
            selectedTools={selectedTools}
            onToggleToolSelection={toggleToolSelection}
            onToolsQueryChange={handleToolsQueryChange}
            onLoadMoreTools={handleLoadMoreTools}
          />
        </div>
      </div>
    </section>
  );
}
