import { useCallback } from "react";
import type { ChatConversation } from "@/lib/types";
import { useAppStore } from "@/lib/store";
import { safeJson } from "@/lib/http";
import { AUTO_CHAT_TITLE_REGEX } from "@/shared/chat-constants";

function isAutoGeneratedTitle(title?: string | null): boolean {
  if (!title) return true;
  return AUTO_CHAT_TITLE_REGEX.test(title.trim());
}

/**
 * Server-side auto-title generation is asynchronous. After a user sends
 * the first message, poll for a fresh title up to 4 times with growing
 * delays (900ms, 1800ms, 2700ms, 3600ms). When a non-auto title arrives,
 * update the Zustand conversation store.
 */
export function useTitleManager(params: {
  authToken: string | null;
  setConversations: (conversations: ChatConversation[]) => void;
}): { pollForAutoTitle: (conversationId: string) => void } {
  const { authToken, setConversations } = params;

  const pollForAutoTitle = useCallback(
    (conversationId: string) => {
      if (!authToken) return;
      void (async () => {
        for (let attempt = 0; attempt < 4; attempt += 1) {
          await new Promise((resolve) => window.setTimeout(resolve, 900 * (attempt + 1)));
          const response = await fetch(`/api/conversations/${conversationId}`, {
            headers: { Authorization: `Bearer ${authToken}` },
          });
          if (!response.ok) continue;
          const payload = await safeJson<{ conversation?: ChatConversation }>(response);
          const serverConversation = payload?.conversation;
          if (!serverConversation || isAutoGeneratedTitle(serverConversation.title)) continue;
          const currentConversations = useAppStore.getState().conversations;
          const nextConversations = currentConversations.map((item) =>
            item.id === conversationId
              ? { ...item, title: serverConversation.title, updated_at: serverConversation.updated_at }
              : item,
          );
          nextConversations.sort((a, b) => {
            if (a.starred !== b.starred) return a.starred ? -1 : 1;
            return new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime();
          });
          setConversations(nextConversations);
          break;
        }
      })();
    },
    [authToken, setConversations],
  );

  return { pollForAutoTitle };
}
