import { Hono } from "hono";
import { z } from "zod";
import { convertToModelMessages, generateText, stepCountIs, streamText } from "ai";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";
import { CHAT_MODEL_CONFIGS, CHAT_SUPPORT_CONTACT, getChatModelConfig } from "../../src/shared/chat-models.js";
import type { Env } from "../env.js";
import { getSupabaseAdmin, getUserFromRequest, json } from "../_lib/server.js";
import { userRateLimit } from "../_lib/rate-limit.js";
import { errMessage, logError, logWarn } from "../_lib/logger.js";
import { runChatWithFallback } from "../_lib/chat-fallback.js";
import { getSystemPrompt } from "../_lib/system-prompt.js";
import { buildExecutionPlanContext, buildQuantContinuationContext, generateExecutionPlan } from "../_lib/chat-handler.js";
import {
  CREATE_CHART_TOOL_NAME,
  compactMcpToolsForModelContext,
  createSyntheticChartTool,
  enforceCreateChartDataPrereq,
  hasPriorNonChartToolOutput,
  selectToolsForChat,
  selectWeakModelQuantTools,
  shouldRequireDataToolCall,
  summarizeQuantEvidence,
  summarizeToolLoopHealth,
} from "../_lib/tool-pipeline.js";
import {
  AUTO_CHAT_TITLE_MODEL,
  approachingThreshold,
  buildAssistantPartsFromFinishEvent,
  buildProviderSafeTools,
  buildToolCatalog,
  compactCreateChartSpec,
  extractLatestUserText,
  getModelUsageStatus,
  getOpenRouterFallbackModels,
  isAutoGeneratedConversationTitle,
  isProviderInvalidRequestError,
  isProviderTimeoutError,
  isRecord,
  loadAuthorizedMcpTools,
  loadConversationDocumentContext,
  logToolSequenceForRequest,
  normalizeToolSchemas,
  projectToolSchemasForModel,
  reserveModelUsageSlot,
  sanitizeArtifactContext,
  sanitizeIncomingDocuments,
  summarizeArtifactContext,
  utcDateStamp,
  generateAutoChatTitleFromFirstMessage,
} from "../_lib/internals.js";
import { compactMessagesForModel as compactUiMessagesForModel } from "../_lib/context.js";
import { parseJson, uuidSchema, dbError } from "../_lib/validation.js";

const toolsBodySchema = z.object({
  mcpToken: z.string().max(512).nullable().optional(),
  query: z.string().max(500).optional(),
  offset: z.number().int().min(0).max(10_000).optional(),
  limit: z.number().int().min(1).max(100).optional(),
});

const chatBodySchema = z.object({
  messages: z.array(z.object({ role: z.string().optional(), parts: z.array(z.unknown()).optional() })).optional(),
  mcpToken: z.string().max(512).nullable().optional(),
  conversationId: uuidSchema,
  modelId: z.string().max(200).nullable().optional(),
  documents: z.unknown().optional(),
  artifactContext: z.unknown().optional(),
});

const chatRoutes = new Hono<{ Bindings: Env }>();

chatRoutes.use("*", userRateLimit("CHAT_LIMITER"));

// ---------------------------------------------------------------------------
// POST /tools — list available tools
// ---------------------------------------------------------------------------

chatRoutes.post("/tools", async (c) => {
  const user = await getUserFromRequest(c.req.raw, c.env);
  if (!user) return json({ error: "Unauthorized" }, 401);

  const parsed = await parseJson(c, toolsBodySchema);
  if (!parsed.ok) return parsed.response;
  const body = parsed.data;

  const supabase = getSupabaseAdmin(c.env);
  const toolLoad = await loadAuthorizedMcpTools({ supabase, user, mcpToken: body.mcpToken, env: c.env });
  if ("response" in toolLoad) return toolLoad.response;

  const query = typeof body.query === "string" ? body.query : "";
  const offset = Math.max(0, body.offset ?? 0);
  const limit = Math.min(100, Math.max(20, body.limit ?? 50));
  const catalog = buildToolCatalog(toolLoad.tools, query);
  const items = catalog.slice(offset, offset + limit);
  const nextOffset = offset + items.length < catalog.length ? offset + items.length : null;

  return c.json({
    totalCount: catalog.length,
    items: items.map(({ name, description, category, recommended }) => ({ name, description, category, recommended })),
    nextOffset,
    hasMore: nextOffset !== null,
  });
});

// ---------------------------------------------------------------------------
// GET /usage — single-model usage
// ---------------------------------------------------------------------------

chatRoutes.get("/usage", async (c) => {
  const user = await getUserFromRequest(c.req.raw, c.env);
  if (!user) return json({ error: "Unauthorized" }, 401);

  const modelId = new URL(c.req.url).searchParams.get("modelId");
  const selectedModel = getChatModelConfig(modelId);
  const supabase = getSupabaseAdmin(c.env);

  const usage = await getModelUsageStatus({
    supabase,
    userId: user.id,
    modelId: selectedModel.id,
    dailyLimit: selectedModel.dailyLimit,
  });
  if (!usage.ok) return json({ error: usage.error }, 500);

  const banner = usage.reached
    ? `Daily ${selectedModel.label} limit reached - ${CHAT_SUPPORT_CONTACT}.`
    : usage.approaching
      ? `${selectedModel.label} limit nearly reached (${usage.remaining} remaining today).`
      : null;

  return c.json({
    modelId: selectedModel.id,
    label: selectedModel.label,
    dailyLimit: selectedModel.dailyLimit,
    used: usage.used,
    remaining: usage.remaining,
    approaching: usage.approaching,
    reached: usage.reached,
    tokens: usage.tokens,
    toolCalls: usage.toolCalls,
    banner,
  });
});

// ---------------------------------------------------------------------------
// GET /usage/all — all-model usage
// ---------------------------------------------------------------------------

chatRoutes.get("/usage/all", async (c) => {
  const user = await getUserFromRequest(c.req.raw, c.env);
  if (!user) return json({ error: "Unauthorized" }, 401);

  const usageDate = utcDateStamp();
  const supabase = getSupabaseAdmin(c.env);
  const { data, error } = await supabase
    .from("uk_chat_model_usage")
    .select("model_id,request_count,total_prompt_tokens,total_completion_tokens,total_tool_calls")
    .eq("user_id", user.id)
    .eq("usage_date", usageDate);

  if (error) return dbError(error, { context: "api/chat/usage/all", publicMessage: "Failed to load usage" });

  type DailyModelUsage = {
    requests: number;
    promptTokens: number;
    completionTokens: number;
    toolCalls: number;
  };
  const usageByModelId = new Map<string, DailyModelUsage>();
  for (const row of data ?? []) {
    const existing = usageByModelId.get(row.model_id);
    const requests = (existing?.requests ?? 0) + (row.request_count ?? 0);
    const promptTokens = (existing?.promptTokens ?? 0) + (row.total_prompt_tokens ?? 0);
    const completionTokens = (existing?.completionTokens ?? 0) + (row.total_completion_tokens ?? 0);
    const toolCalls = (existing?.toolCalls ?? 0) + (row.total_tool_calls ?? 0);
    usageByModelId.set(row.model_id, { requests, promptTokens, completionTokens, toolCalls });
  }

  const models = CHAT_MODEL_CONFIGS.map((model) => {
    const usage = usageByModelId.get(model.id);
    const used = usage?.requests ?? 0;
    const remaining = Math.max(0, model.dailyLimit - used);
    const reached = remaining <= 0;
    const approaching = !reached && remaining <= approachingThreshold(model.dailyLimit);
    return {
      id: model.id,
      label: model.label,
      dailyLimit: model.dailyLimit,
      used,
      remaining,
      approaching,
      reached,
      tokens: {
        prompt: usage?.promptTokens ?? 0,
        completion: usage?.completionTokens ?? 0,
        total: (usage?.promptTokens ?? 0) + (usage?.completionTokens ?? 0),
      },
      toolCalls: usage?.toolCalls ?? 0,
    };
  });

  return c.json({ models });
});

// ---------------------------------------------------------------------------
// POST / — main streaming chat
// ---------------------------------------------------------------------------

chatRoutes.post("/", async (c) => {
  const user = await getUserFromRequest(c.req.raw, c.env);
  if (!user) return json({ error: "Unauthorized" }, 401);

  const parsed = await parseJson(c, chatBodySchema);
  if (!parsed.ok) return parsed.response;
  const body = parsed.data;

  const supabase = getSupabaseAdmin(c.env);

  const { data: conversation } = await supabase
    .from("uk_chat_conversations")
    .select("id,title")
    .eq("id", body.conversationId)
    .eq("user_id", user.id)
    .single();
  if (!conversation) return json({ error: "Conversation not found" }, 404);

  const selectedModel = getChatModelConfig(body.modelId);
  const openrouter = createOpenRouter({ apiKey: c.env.OPENROUTER_API_KEY });
  const incomingDocuments = sanitizeIncomingDocuments(body.documents);
  const artifactContext = summarizeArtifactContext(sanitizeArtifactContext(body.artifactContext));

  // --- Usage reservation ---
  const usageReservation = await reserveModelUsageSlot({
    supabase,
    userId: user.id,
    modelId: selectedModel.id,
    dailyLimit: selectedModel.dailyLimit,
  });
  if (!usageReservation.ok) {
    if (usageReservation.error) return json({ error: usageReservation.error }, 500);
    return json(
      {
        error: `You've hit today's conservative limit for ${selectedModel.label}. Please try again tomorrow - ${CHAT_SUPPORT_CONTACT}.`,
        code: "MODEL_USAGE_LIMIT_REACHED",
      },
      429,
    );
  }

  // --- MCP tool loading ---
  const toolLoad = await loadAuthorizedMcpTools({
    supabase,
    user,
    mcpToken: body.mcpToken,
    conversationId: body.conversationId,
    env: c.env,
  });
  if ("response" in toolLoad) return toolLoad.response;

  // --- Tool scoping ---
  const tools = compactMcpToolsForModelContext(toolLoad.tools, {
    outputBudgetChars: selectedModel.toolOutputBudgetChars,
  });
  const latestUserQuery = extractLatestUserText(body.messages);
  const requireDataToolCall = shouldRequireDataToolCall(latestUserQuery);
  const quantPrefetchStepLimit = Math.max(
    1,
    Math.min(selectedModel.maxPrefetchToolStepsForQuant, selectedModel.toolStepLimit),
  );
  const quantMainStepLimit = Math.max(
    2,
    Math.min(selectedModel.maxMainToolStepsForQuant, selectedModel.toolStepLimit),
  );
  const weakQuantToolRestrictionApplied = requireDataToolCall && selectedModel.restrictQuantToolsForWeakModels;
  const priorDataToolOutputExists = hasPriorNonChartToolOutput(body.messages);
  const allowCreateChartTool = !requireDataToolCall || priorDataToolOutputExists;
  const selectedBaseTools = selectToolsForChat(tools, latestUserQuery, 18);
  const quantScopedBaseTools = weakQuantToolRestrictionApplied
    ? selectWeakModelQuantTools(selectedBaseTools, latestUserQuery, { minimumTools: 3 })
    : selectedBaseTools;
  const scopedTools = {
    ...quantScopedBaseTools,
    ...(allowCreateChartTool ? { [CREATE_CHART_TOOL_NAME]: createSyntheticChartTool(compactCreateChartSpec) } : {}),
  };
  const guardedTools = enforceCreateChartDataPrereq(scopedTools);

  // --- Tool schema normalization and projection ---
  const { projectedTools, projectedToolNames } = projectToolSchemasForModel(guardedTools, selectedModel.id);
  const { normalizedTools, normalizedToolNames } = normalizeToolSchemas(projectedTools);
  const { safeTools, safeToOriginal, renamedPairs } = buildProviderSafeTools(normalizedTools);

  const quantitativeSafeTools = Object.fromEntries(
    Object.entries(safeTools).filter(([toolName]) => toolName !== CREATE_CHART_TOOL_NAME),
  );
  const quantitativeReducedSafeTools = selectWeakModelQuantTools(quantitativeSafeTools, latestUserQuery, {
    minimumTools: 3,
  });

  if (projectedToolNames.length > 0) {
    logWarn("[api/chat] Applied model-specific tool schema projection", {
      modelId: selectedModel.id,
      projectedCount: projectedToolNames.length,
      projectedToolNames,
    });
  }
  if (normalizedToolNames.length > 0) {
    logWarn("[api/chat] Normalized Gemini-incompatible MCP schemas", {
      normalizedCount: normalizedToolNames.length,
      normalizedToolNames,
    });
  }
  logWarn("[api/chat] Scoped tool catalog for request", {
    totalTools: Object.keys(tools).length,
    selectedTools: Object.keys(scopedTools).length,
    query: latestUserQuery.slice(0, 180),
    requireDataToolCall,
    allowCreateChartTool,
    priorDataToolOutputExists,
    weakQuantToolRestrictionApplied,
  });
  if (renamedPairs.length > 0) {
    logWarn("[api/chat] Remapped tool names for provider compatibility", {
      renamedCount: renamedPairs.length,
      renamedPairs: renamedPairs.slice(0, 12),
    });
  }

  // --- Auto chat title ---
  const latestUserMessage = [...(body.messages ?? [])].reverse().find((message) => message.role === "user");
  let shouldAutoNameConversation = false;
  if (latestUserMessage && isAutoGeneratedConversationTitle(conversation.title)) {
    const { data: existingUserMessage } = await supabase
      .from("uk_chat_messages")
      .select("id")
      .eq("conversation_id", body.conversationId)
      .eq("role", "user")
      .limit(1)
      .maybeSingle();
    shouldAutoNameConversation = !existingUserMessage;
  }

  // --- Persist user message ---
  if (latestUserMessage) {
    const userParts = Array.isArray(latestUserMessage.parts) ? [...latestUserMessage.parts] : [];
    incomingDocuments.forEach((document) => userParts.push(document));
    userParts.push({ type: "meta-model", modelId: selectedModel.id });
    const { error: insertUserError } = await supabase.from("uk_chat_messages").insert({
      conversation_id: body.conversationId,
      role: "user",
      parts: userParts,
    });
    if (insertUserError) {
      logError("[api/chat] Failed to persist user message", {
        conversationId: body.conversationId,
        userId: user.id,
        error: insertUserError.message,
        code: insertUserError.code ?? null,
      });
      return json({ error: "Failed to save your message. Please try again." }, 500);
    }
  }

  // --- Fire-and-forget auto title ---
  if (shouldAutoNameConversation) {
    const firstUserText = extractLatestUserText(body.messages);
    if (firstUserText) {
      const autoTitlePromise = (async () => {
        const generatedTitle = await generateAutoChatTitleFromFirstMessage(
          firstUserText,
          openrouter.chat(AUTO_CHAT_TITLE_MODEL),
        );
        if (!generatedTitle) return;
        const { error: autoTitleUpdateError } = await supabase
          .from("uk_chat_conversations")
          .update({ title: generatedTitle, updated_at: new Date().toISOString() })
          .eq("id", body.conversationId!)
          .eq("user_id", user.id)
          .eq("title", conversation.title);
        if (autoTitleUpdateError) {
          logWarn("[api/chat] Failed to persist auto chat title", {
            conversationId: body.conversationId,
            userId: user.id,
            error: autoTitleUpdateError.message,
            code: autoTitleUpdateError.code ?? null,
          });
        }
      })();
      c.executionCtx.waitUntil(
        autoTitlePromise.catch((err) => {
          logError("[api/chat] Auto-title background task threw", {
            conversationId: body.conversationId,
            userId: user.id,
            error: errMessage(err),
          });
        }),
      );
    }
  }

  // --- Document context ---
  const documentContext = await loadConversationDocumentContext({
    supabase,
    conversationId: body.conversationId,
  });

  // --- Quantitative evidence prefetch ---
  const quantPolicyActive = requireDataToolCall && selectedModel.runEvidencePrefetchForQuant;
  const quantTelemetry: Record<string, unknown> = {
    quantPolicyActive,
    minNonChartCalls: selectedModel.minDataToolCallsForQuant,
    continuationInjected: false,
    fallbackPath: "none",
    quantPrefetchStepLimit,
    quantMainStepLimit,
    weakQuantToolRestrictionApplied,
  };

  const planSteps = requireDataToolCall
    ? await generateExecutionPlan({
        model: openrouter.chat(selectedModel.providerModel),
        query: latestUserQuery,
        availableTools: Object.keys(scopedTools),
        maxSteps: Math.min(5, selectedModel.toolStepLimit),
      })
    : [];
  const planContext = buildExecutionPlanContext(planSteps);
  const systemPromptBase = getSystemPrompt(new Date(), selectedModel.id);
  let withPlanContext = planContext ? `${systemPromptBase}\n\n${planContext}` : systemPromptBase;
  let quantContinuationContext = "";
  let forceReducedMainTools = false;
  const compactedMessages = compactUiMessagesForModel(body.messages ?? []);

  if (quantPolicyActive) {
    try {
      const prefetch = await generateText({
        model: openrouter.chat(selectedModel.providerModel),
        system: withPlanContext,
        prompt: [
          "Run tool calls to gather concrete numeric evidence for this quantitative query.",
          "Do not finalise an answer yet.",
          "Prefer non-create_chart data tools first.",
          "",
          `User query: ${latestUserQuery}`,
        ].join("\n"),
        tools: quantitativeSafeTools as Parameters<typeof streamText>[0]["tools"],
        toolChoice: "required",
        stopWhen: stepCountIs(quantPrefetchStepLimit),
        temperature: 0,
      });

      const prefetchSummary = summarizeQuantEvidence(prefetch, selectedModel.minDataToolCallsForQuant);
      const prefetchLoopHealth = summarizeToolLoopHealth(prefetch);
      quantTelemetry.prefetchSummary = prefetchSummary;
      quantTelemetry.prefetchLoopHealth = prefetchLoopHealth;
      quantTelemetry.prefetchToolCallCount = prefetchSummary.toolCallCount;
      quantTelemetry.prefetchNonChartCalls = prefetchSummary.nonChartToolCallCount;
      quantTelemetry.prefetchDataBearingResults = prefetchSummary.dataBearingResultCount;
      quantTelemetry.prefetchFirstTool = prefetchSummary.firstToolName;
      quantTelemetry.prefetchFirstToolMetadataLike = prefetchSummary.firstToolMetadataLike;
      quantTelemetry.prefetchHasEnoughEvidence = prefetchSummary.hasEnoughEvidence;

      if (
        !prefetchSummary.hasEnoughEvidence ||
        (selectedModel.enableMetadataRetryForQuant && prefetchSummary.firstToolMetadataLike)
      ) {
        quantContinuationContext = buildQuantContinuationContext({
          minNonChartCalls: selectedModel.minDataToolCallsForQuant,
          firstToolMetadataLike: prefetchSummary.firstToolMetadataLike,
          forceNoChartFirst: true,
        });
        quantTelemetry.continuationInjected = true;
      }

      if (prefetchLoopHealth.maxRepeatCount > selectedModel.maxRepeatedToolCallsPerTurn) {
        forceReducedMainTools = true;
        quantTelemetry.prefetchLoopBreakerTriggered = true;
        quantTelemetry.prefetchMaxRepeatCount = prefetchLoopHealth.maxRepeatCount;
        quantContinuationContext = [
          quantContinuationContext,
          "TOOL LOOP SAFETY: avoid repeating the same tool call with identical parameters.",
          "If one call fails, switch to a different retrieval tool or narrower filters.",
        ]
          .filter(Boolean)
          .join("\n");
      }

      const prefetchToolsLine = Array.isArray(prefetch.steps)
        ? prefetch.steps
            .flatMap((step) =>
              Array.isArray((step as { toolCalls?: unknown[] }).toolCalls)
                ? ((step as { toolCalls?: unknown[] }).toolCalls as unknown[])
                : [],
            )
            .map((call) =>
              isRecord(call) && typeof call.toolName === "string" ? call.toolName : null,
            )
            .filter((name): name is string => Boolean(name))
            .slice(0, 8)
            .join(", ")
        : "";
      if (prefetchToolsLine) {
        compactedMessages.push({
          role: "assistant",
          parts: [{ type: "text", text: `Evidence prefetch calls: ${prefetchToolsLine}` }],
        });
      }
    } catch (error) {
      quantTelemetry.prefetchError = error instanceof Error ? error.message : String(error);
    }
  }

  if (quantContinuationContext) {
    withPlanContext = `${withPlanContext}\n\n${quantContinuationContext}`;
  }

  const systemPrompt = [withPlanContext, documentContext, artifactContext].filter(Boolean).join("\n\n");
  // UIMessage generic is unknown at this boundary; SDK typing is intentionally narrow.
  const modelMessages = await convertToModelMessages(compactedMessages as never);

  if (Array.isArray(body.messages) && compactedMessages.length !== body.messages.length) {
    logWarn("[api/chat] Compacted message history for model context", {
      originalCount: body.messages.length,
      compactedCount: compactedMessages.length,
    });
  }

  const compactedChars = compactedMessages.reduce(
    (sum, message) =>
      sum +
      message.parts.reduce((partSum, part) => partSum + (typeof part.text === "string" ? part.text.length : 0), 0),
    0,
  );
  if (compactedChars > 40_000) {
    logWarn("[api/chat] Compacted message payload is still large", {
      compactedCount: compactedMessages.length,
      compactedChars,
    });
  }

  // --- onFinish callback ---
  const onAssistantFinish: Parameters<typeof streamText>[0]["onFinish"] = async (event) => {
    if (requireDataToolCall) {
      const finalEvidence = summarizeQuantEvidence(event, selectedModel.minDataToolCallsForQuant);
      quantTelemetry.finalEvidence = finalEvidence;
      quantTelemetry.finalHasEnoughEvidence = finalEvidence.hasEnoughEvidence;
    }
    logToolSequenceForRequest({
      event,
      conversationId: body.conversationId,
      modelId: selectedModel.id,
      providerModel: selectedModel.providerModel,
      quantTelemetry,
    });

    const persistPromise = (async () => {
      const assistantParts = buildAssistantPartsFromFinishEvent(event, (name) => safeToOriginal.get(name) ?? name);
      const { error: assistantInsertError } = await supabase.from("uk_chat_messages").insert({
        conversation_id: body.conversationId!,
        role: "assistant",
        parts: assistantParts,
      });
      if (assistantInsertError) {
        logError("[api/chat] Failed to persist assistant message", {
          conversationId: body.conversationId,
          userId: user.id,
          error: assistantInsertError.message,
          code: assistantInsertError.code ?? null,
        });
        return;
      }

      const { error: updateConversationError } = await supabase
        .from("uk_chat_conversations")
        .update({ updated_at: new Date().toISOString() })
        .eq("id", body.conversationId!)
        .eq("user_id", user.id);
      if (updateConversationError) {
        logError("[api/chat] Failed to update conversation timestamp", {
          conversationId: body.conversationId,
          userId: user.id,
          error: updateConversationError.message,
          code: updateConversationError.code ?? null,
        });
      }
    })();

    const tokenTrackingPromise = (async () => {
      const usage = isRecord(event.usage) ? (event.usage as Record<string, unknown>) : null;
      const promptTokens =
        (typeof usage?.["inputTokens"] === "number" ? usage["inputTokens"] : null) ??
        (typeof usage?.["promptTokens"] === "number" ? usage["promptTokens"] : null) ??
        0;
      const completionTokens =
        (typeof usage?.["outputTokens"] === "number" ? usage["outputTokens"] : null) ??
        (typeof usage?.["completionTokens"] === "number" ? usage["completionTokens"] : null) ??
        0;
      const toolCallCount = Array.isArray(event.toolCalls) ? event.toolCalls.length : 0;
      if (promptTokens === 0 && completionTokens === 0 && toolCallCount === 0) return;

      const { error: tokenError } = await supabase.rpc("increment_token_usage", {
        p_user_id: user.id,
        p_model_id: selectedModel.id,
        p_usage_date: utcDateStamp(),
        p_prompt_tokens: promptTokens,
        p_completion_tokens: completionTokens,
        p_tool_calls: toolCallCount,
      });
      if (tokenError) {
        logError("[api/chat] Failed to persist token usage", {
          conversationId: body.conversationId,
          userId: user.id,
          modelId: selectedModel.id,
          promptTokens,
          completionTokens,
          toolCallCount,
          error: tokenError.message,
        });
      }
    })();

    const safePersist = persistPromise.catch((err) => {
      logError("[api/chat] Persist background task threw", {
        conversationId: body.conversationId,
        userId: user.id,
        error: err instanceof Error ? err.message : String(err),
      });
    });
    const safeTokens = tokenTrackingPromise.catch((err) => {
      logError("[api/chat] Token tracking background task threw", {
        conversationId: body.conversationId,
        userId: user.id,
        modelId: selectedModel.id,
        error: err instanceof Error ? err.message : String(err),
      });
    });
    c.executionCtx.waitUntil(safePersist);
    c.executionCtx.waitUntil(safeTokens);
    // Errors are swallowed into logs; Promise.all never rejects here by design — response succeeds even if persist/token tracking fail.
    await Promise.all([safePersist, safeTokens]);
  };

  // --- Streaming with fallback chain ---
  const fallbackModels = getOpenRouterFallbackModels(selectedModel.id);

  const tryStream = (options: {
    includeFallbackModels: boolean;
    includeTools: boolean;
    requireToolCall: boolean;
    toolsOverride?: Parameters<typeof streamText>[0]["tools"];
    systemOverride?: string;
    stepLimitOverride?: number;
  }) =>
    streamText({
      model: openrouter.chat(selectedModel.providerModel, {
        extraBody: options.includeFallbackModels && fallbackModels.length > 0 ? { models: fallbackModels } : undefined,
      }),
      messages: modelMessages,
      tools: options.includeTools
        ? (options.toolsOverride ?? (safeTools as Parameters<typeof streamText>[0]["tools"]))
        : undefined,
      toolChoice: options.includeTools ? (options.requireToolCall ? "required" : "auto") : undefined,
      stopWhen: stepCountIs(
        options.stepLimitOverride ?? (requireDataToolCall ? quantMainStepLimit : selectedModel.toolStepLimit),
      ),
      temperature: selectedModel.toolTemperature,
      system: options.systemOverride ?? systemPrompt,
      onFinish: onAssistantFinish,
    });

  const result = runChatWithFallback({
    tryStream,
    primary: {
      includeFallbackModels: true,
      includeTools: true,
      requireToolCall: requireDataToolCall,
      toolsOverride: forceReducedMainTools
        ? (quantitativeReducedSafeTools as Parameters<typeof streamText>[0]["tools"])
        : undefined,
    },
    requireDataToolCall,
    quantitativeSafeTools: quantitativeSafeTools as Parameters<typeof streamText>[0]["tools"],
    quantitativeReducedSafeTools: quantitativeReducedSafeTools as Parameters<typeof streamText>[0]["tools"],
    systemPrompt,
    quantMainStepLimit,
    modelId: selectedModel.id,
    providerModel: selectedModel.providerModel,
    telemetry: quantTelemetry,
  });

  return result.toUIMessageStreamResponse({
    // SDK narrows to its own UIMessage generic; request payload is unknown-shaped.
    originalMessages: (body.messages ?? []) as never,
  });
});

export { chatRoutes };
